[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
address = "0.0.0.0"
maxUploadSize = 200
enableCORS = false

[browser]
gatherUsageStats = false

[logger]
level = "info"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[runner]
fastReruns = true
